### PR TITLE
Update ERRANT to use with spaCy 3

### LINKED ISSUE #24: Errant incompatible with spacy 3
Note to self: update errant to work with spacy 3.

### PR DESCRIPTION
**Pull request by Frost45**
Our team is working on using ERRANT with our own custom tokenisation.

As a result, we have updated this repo to work with spaCy 3.

Any comments and suggestions are much appreciated!

Closes #24

### CODE REVIEW

**Comment by chrisjbryant** [comment]
Hey! Thanks for this!
I had a quick look, and everything seems good, but I'll try to work on evaluating the speed at some point.

**Comment by Frost45** [comment]
Sounds good! Thank you for taking a look :)

**Comment by akesh1235** [comment]
@chrisjbryant 
@Frost45 
### **I got this error**

  File "C:\Users\inti004\Desktop\apideployenv\Lib\site-packages\errant\annotator.py", line 26, in parse
    text = self.nlp(text)
           ^^^^^^^^^^^^^^

**TypeError:** Argument 'string' has incorrect type (expected str, got spacy.tokens.doc.Doc)

**Comment by chrisjbryant** [comment]
What command are you running? Or is this your own script?
That error makes me think you're passing text that has already been processed by spacy to errant, in which case you don't need to parse it again.

**Comment by chrisjbryant** [comment]
I finally got around to doing this myself and running some tests etc. Sorry about the delay!

**Pull request closed without merging**
